function [numTurbines, turbinePower, powerNeeded] = calcNumTurbines(P,pop,WS)
% This function calculates the total power outputted by a turbine in 2016 
% in Calgary and thus the number of turbines needed to power the city

convertedPower = 0; % initializes converted power value 
for j = 1:length(WS) % iterates through the 8760 hours 
    if WS(j) ~= 0   % takes every index of the matrix except for the 0th one
        convertedPower = convertedPower + P(WS(j)); % sums the corresponding powers for each wind speed to get total power in Wh
    end
end

turbinePower = sum(convertedPower)/1.e+6; % calculates the power generated by one turbine in 2016 in MWh

powerNeeded = pop*16.5; % calculates the power needed for the city in one year

numTurbines = ceil(powerNeeded/turbinePower); % calculates the number of turbines needed and rounds to next integer

end

